TRAIN:
  ENABLE: True
  DATASET: MOE
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
MODEL:
  MODEL_NAME: transformer_fusion
  INPUT_TOKENS: 3
  TOKEN_SIZE: 768
  NUM_HEADS: 8
  NUM_LAYERS: 2
  DROPOUT: 0.5
PRETRAINED: False


