TRAIN:
  ENABLE: True
  DATASET: MOE
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: /playpen-nas-ssd2/asdunnbe/TimeSformer_egoexo/full_run_outputs/Dance/Dance_video_full/checkpoints/checkpoint_epoch_00015.pyth
  # FINETUNE: TRUE #If using pretrained_checkpoint for Kinetics, HowTo100M or EgoVLPv2, set to True
MODEL:
  MODEL_NAME: moe_fusion
  NUM_CLASSES: 4
  NUM_EXPERTS: 3
  INPUT_TOKENS: 4
  TOKEN_SIZE: 768
  CAPACITY_FACTOR: 2
  OUT_METHOD: weighted
PRETRAINED: false
