TRAIN:
  ENABLE: True
  DATASET: MOE
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
MODEL:
  MODEL_NAME: transformer_fusion
  NUM_CLASSES: 4
  INPUT_TOKENS: 4
  TOKEN_SIZE: 768
  NUM_HEADS: 12
  NUM_LAYERS: 3
  DROPOUT: 0.3
PRETRAINED: False


